# Copyright 2016 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# Gateway service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 32000
  selector:
    name: gateway
  type: NodePort
---
    
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: amalgam8/a8-sidecar:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        args:
        - /usr/bin/run_filebeat.sh
        env:
        - name: A8_PROXY
          value: "true"
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_REGISTRY_BACKEND
          value: kubernetes
        - name: A8_SERVICE
          value: gateway
        - name: A8_LOGSTASH_SERVER
          value: $(LOGSERVER_SERVICE_HOST):8092
        - name: A8_CONTROLLER_POLL
          value: 5s
---
    
##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  clusterIP: None
  ports:
  - port: 9080
    protocol: TCP
    name: http
  selector:
    name: details
---
    
apiVersion: v1
kind: ReplicationController
metadata:
  name: details-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: details
        version: v1
    spec:
      containers:
      - name: details
        image: amalgam8/a8-examples-bookinfo-details:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
    
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  clusterIP: None
  ports:
  - port: 9080
    protocol: TCP
    name: http
  selector:
    name: ratings
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: ratings-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: amalgam8/a8-examples-bookinfo-ratings:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
##################################################################################################
# Reviews service
##################################################################################################

apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  clusterIP: None
  ports:
  - port: 9080
    protocol: TCP
    name: http
  selector:
    name: reviews
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
    
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - /usr/bin/run_filebeat.sh
        ports:
        - containerPort: 6379
        env:
        - name: A8_PROXY
          value: "true"
        - name: A8_REGISTRY_BACKEND
          value: kubernetes
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_CONTROLLER_POLL
          value: 5s
        - name: A8_LOGSTASH_SERVER
          value: $(LOGSERVER_SERVICE_HOST):8092
        - name: A8_SERVICE
          value: reviews:version=v2
---
    
apiVersion: v1
kind: ReplicationController
metadata:
  name: reviews-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: amalgam8/a8-examples-bookinfo-reviews:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - /usr/bin/run_filebeat.sh
        ports:
        - containerPort: 6379
        env:
        - name: A8_PROXY
          value: "true"
        - name: A8_REGISTRY_BACKEND
          value: kubernetes
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_CONTROLLER_POLL
          value: 5s
        - name: A8_LOGSTASH_SERVER
          value: $(LOGSERVER_SERVICE_HOST):8092
        - name: A8_SERVICE
          value: reviews:version=v3
---
    
##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
spec:
  clusterIP: None
  ports:
  - port: 9080
    protocol: TCP
    name: http
  selector:
    name: productpage
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: productpage-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: amalgam8/a8-examples-bookinfo-productpage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      - name: serviceproxy
        image: amalgam8/a8-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - /usr/bin/run_filebeat.sh
        ports:
        - containerPort: 6379
        env:
        - name: A8_PROXY
          value: "true"
        - name: A8_REGISTRY_BACKEND
          value: kubernetes
        - name: A8_CONTROLLER_URL
          value: http://$(CONTROLLER_SERVICE_HOST):$(CONTROLLER_SERVICE_PORT)
        - name: A8_CONTROLLER_POLL
          value: 5s
        - name: A8_LOGSTASH_SERVER
          value: $(LOGSERVER_SERVICE_HOST):8092
        - name: A8_SERVICE
          value: productpage:version=v1
